name: Trigger Build On Merge
on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change gradlew executable permission
        run: chmod +x ./gradlew

      - name: Build Gradle
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: "app/build/outputs/apk/debug/*.apk"

      - name: Upload Artifact To Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Android-CICD-Testers
          releaseNotes: "Hey App Monks! Try to login with your google account then download and test this build."
          file: "app/build/outputs/apk/debug/*.apk"